controllers/ContactBookController.php
<?php

namespace app\controllers;

use app\models\ContactBook;
use Yii;
use yii\web\Controller;

/**
 * ContactBookController implements the CRUD actions for ContactBook model.
 */
class ContactBookController extends Controller
{

    public function actionCreate()
    {
        $name = Yii::$app->request->get('name');
        $number = Yii::$app->request->get('number');

        $contact = new ContactBook();

        $contact->name = $name;
        $contact->tel_number = $number;
        if ($contact->save()) {
            return json_encode(['success' => true, 'message' => 'Контакт успешно добавлен']);
        } else {
            return json_encode(['success' => false, 'message' => 'Ошибка при добавлении контакта']);
        }

    }

    public function actionDel($id)
    {
        $contact = ContactBook::find()
            ->where(['id' => $id])
            ->one();

        if ($contact->delete()) {
            return json_encode(['success' => true, 'message' => 'Контакт успешно удален']);
        } else {
            return json_encode(['success' => false, 'message' => 'Ошибка при удалении контакта']);
        }
    }

}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\ContactBook;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $contacts = ContactBook::find()->all();

        $this->layout = false;
        return $this->render('index.php', [
            'contacts' => $contacts,
        ]);
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if (Yii::$app->request->post()) {
            if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
                Yii::$app->session->setFlash('contactFormSubmitted');
                return $this->refresh();
            }
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
}

views/site/about.php
<?php

/** @var yii\web\View $this */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */
/** @var app\models\ContactForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;
use yii\captcha\Captcha;

$this->title = 'Contact';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

        <div class="alert alert-success">
            Thank you for contacting us. We will respond to you as soon as possible.
        </div>

        <p>
            Note that if you turn on the Yii debugger, you should be able
            to view the mail message on the mail panel of the debugger.
            <?php if (Yii::$app->mailer->useFileTransport): ?>
                Because the application is in development mode, the email is not sent but saved as
                a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
                Please configure the <code>useFileTransport</code> property of the <code>mail</code>
                application component to be false to enable email sending.
            <?php endif; ?>
        </p>

    <?php else: ?>

        <p>
            If you have business inquiries or other questions, please fill out the following form to contact us.
            Thank you.
        </p>

        <div class="row">
            <div class="col-lg-5">

                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                    <?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

                    <?= $form->field($model, 'email') ?>

                    <?= $form->field($model, 'subject') ?>

                    <?= $form->field($model, 'body')->textarea(['rows' => 6]) ?>

                    <?= $form->field($model, 'verifyCode')->widget(Captcha::class, [
                        'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                    ]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>

    <?php endif; ?>
</div>

views/site/error.php
<?php

/** @var yii\web\View $this */
/** @var string $name */
/** @var string $message */
/** @var Exception$exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Книга контактов</title>
    <!-- Подключаем шрифт Open Sans -->
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400&display=swap" rel="stylesheet">
    <!-- Подключаем Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <style>

        body {
            font-family: "Open Sans", sans-serif;
            background-color: #f0f0f0;
        }

        .container {
            background-color: #fff;
            padding: 30px;
            padding-bottom: 4%;
            border-radius: 5px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
            max-width: 400px;
            margin: 1cm auto;
            margin-bottom: 30px;
            position: relative;
        }

        hr {
            border: none;
            border-top: 1px solid #eee;
            margin: 10px 0;
        }

        .form-group input[type="text"] {
            color: #555;
            background-color: #f9f9f9;
            border-color: #eee;
            border-radius: 5px;
            padding-left: 30px;
        }

        .form-group input[type="text"]:focus {
            outline: none;
            box-shadow: 0 0 4px rgba(0, 0, 0, 0.2);
        }

        .btn-add {
            background-color: #4d59a1;
            color: #fff;
            border-radius: 5px;
            position: absolute;
            right: 20px;
            bottom: 28px;
        }

        .contact-list {
            margin-top: 1cm;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.2);
            padding: 30px;
            border-radius: 5px;
            max-width: 400px;
        }

        .contact-item {
            padding: 10px 0;
            position: relative;
            font-size: 12.36pt;
        }

        .contact-item hr {
            margin: 10px 0;
        }

        .contact-item .delete-contact {
            color: #000;
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
            cursor: pointer;
        }

        .contact-item .phone {
            font-size: 10.88pt;
        }

        .container h2 {
            font-size: 12.36pt;
            margin-top: 0;
            padding-bottom: 13px;
        }
    </style>
</head>
<body>
<div class="container">
    <div class="text-left">
        <h2>Добавить контакт</h2>
        <hr>
    </div>
    <form class="form">
        <div class="form-group">
            <input type="text" class="form-control" id="name" required placeholder="Имя">
        </div>
        <div class="form-group">
            <input type="text" class="form-control" id="number" required placeholder="Телефон" oninput="this.value = this.value.replace(/[^\d+]/g, '');">
        </div>
        <button type="submit" class="btn btn-add">Добавить</button>
    </form>
</div>
<div class="container contact-list">
    <div class="text-left">
        <h2>Список контактов</h2>
        <hr>
    </div>
    <?php
    if ($contacts) {
        foreach ($contacts as $c) {
            ?>
            <div class="contact-item">
                <?= $c->name ?>
                <br>
                <span class="phone"><?= $c->tel_number ?></span>
                <hr>
                <span class="delete-contact" data-id="<?= $c->id ?>">✕</span>
            </div>
            <?php
        }
    }
    ?>
</div>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script>
    $(document).on("click", ".btn-add", function (event) {
        event.preventDefault();
        var name = $("#name").val();
        var number = $("#number").val();

        $.ajax({
            type: 'GET',
            url: "<?= \yii\helpers\Url::to(['contact-book/create']) ?>",
            dataType: 'json',
            data: {
                name: name,
                number: number
            },
            success: function (response) {
                location.reload();
            },
            error: function (xhr, status, error) {
                // Обработка ошибки
                console.log(xhr.responseText);
            }
        });

        $("#name").val("");
        $("#number").val("");
    });

    $(document).on("click", ".delete-contact", function () {
        var contactId = $(this).data("id");

        $.ajax({
            type: 'GET',
            url: "<?= \yii\helpers\Url::to(['contact-book/del']) ?>",
            dataType: 'json',
            data: {
                id: contactId
            },
            success: function (response) {
                if (response.success) {

                    location.reload();
                } else {
                    console.log(response.message);
                }
            },
            error: function (xhr, status, error) {
                console.log(xhr.responseText);
            }
        });
    });
</script>
</body>
</html>

views/site/login.php
<?php

/** @var yii\web\View $this */
/** @var yii\bootstrap5\ActiveForm $form */

/** @var app\models\LoginForm $model */

use yii\bootstrap5\ActiveForm;
use yii\bootstrap5\Html;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">

            <?php $form = ActiveForm::begin([
                'id' => 'login-form',
                'fieldConfig' => [
                    'template' => "{label}\n{input}\n{error}",
                    'labelOptions' => ['class' => 'col-lg-1 col-form-label mr-lg-3'],
                    'inputOptions' => ['class' => 'col-lg-3 form-control'],
                    'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
                ],
            ]); ?>

            <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

            <?= $form->field($model, 'password')->passwordInput() ?>

            <?= $form->field($model, 'rememberMe')->checkbox([
                'template' => "<div class=\"custom-control custom-checkbox\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
            ]) ?>

            <div class="form-group">
                <div>
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>
            </div>

            <?php ActiveForm::end(); ?>

            <div style="color:#999;">
                You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
                To modify the username/password, please check out the code <code>app\models\User::$users</code>.
            </div>

        </div>
    </div>
</div>